### PR TITLE
relax upper bound on base for GHC 7.10

### PR DESCRIPTION
**Pull request by alanz**

### CODE REVIEW

**Comment by phaazon** [comment]
I’d love to test on GHC 7.10, but I haven’t it installed, and I don’t know how to do so yet :(

**Comment by d12frosted** [comment]
Just tested your packages with ghc-7.10.1-rc1, cabal-1.23.0 on OS X 10.10.2 and it builds without errors.

**Comment by phaazon** [comment]
Ok, I guess I can merge your PR then. Thank you :)

**Comment by alanz** [comment]
Thanks

**Comment by d12frosted** [comment]
Great! Thank @alanz and @phaazon !

**Pull request merged**
